{% set version = "0.57.0" %}

package:
  name: memory_profiler
  version: {{ version }}

source:
  fn: memory_profiler-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/memory_profiler/memory_profiler-{{ version }}.tar.gz
  sha256: 23b196f91ea9ac9996e30bfab1e82fecc30a4a1d24870e81d1e81625f786a2c3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - mprof = mprof:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - psutil

test:
  imports:
    - memory_profiler
  commands:
    - mprof list
    - python -m memory_profiler --help

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD 3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'A module for monitoring memory usage of a python program'
  dev_url: https://github.com/pythonprofilers/memory_profiler

extra:
  recipe-maintainers:
    - jakirkham
    - carlodri
