{% set version = "0.52.0" %}

package:
  name: memory_profiler
  version: {{ version }}

source:
  fn: memory_profiler-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/memory_profiler/memory_profiler-{{ version }}.tar.gz
  sha256: e38627e66ca787f56ad2898699e07cb7ae2049a7dc075d535367cd882c417b9a

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - psutil

test:
  imports:
    - memory_profiler
  commands:
    - mprof list
    - python -m memory_profiler --help

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD 3-Clause
  license_family: BSD
  # Not yet included. Please see PR for addition.
  #
  # https://github.com/fabianp/memory_profiler/pull/124
  #
  # license_file: COPYING
  summary: A module for monitoring memory usage of a python program

extra:
  recipe-maintainers:
    - jakirkham
