{% set version = "0.47" %}

package:
  name: memory_profiler
  version: {{ version }}

source:
  fn: memory_profiler-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/memory_profiler/memory_profiler-{{ version }}.tar.gz
  sha256: e992f2a341a5332dad1ad4a008eeac7cfe78c7ea4abdf7535a3e7e79093328cb

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - psutil

test:
  imports:
    - memory_profiler

  commands:
    - mprof list
    - python -m memory_profiler --help

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD 3-Clause
  license_family: BSD
  license_file: COPYING
  summary: A module for monitoring memory usage of a python program
  description: |
    Memory_profiler is a Python module for monitoring memory consumption of a
    process as well as line-by-line analysis of memory consumption for Python
    programs.
  doc_url: https://pypi.python.org/pypi/memory_profiler
  doc_source_url: https://github.com/fabianp/memory_profiler/blob/master/README.rst
  dev_url: https://github.com/fabianp/memory_profiler

extra:
  recipe-maintainers:
    - jakirkham
