# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YqRV20Ou/737GaffyBUIJiVpOW/pZGrgifsJ41WNBLUqQ36esutFDYoh2wBAUAUhPhjvlDBAl7vuimBSiRLYNCdJLdjmbxvQpfKEuy0cvM51HwVl+g5EVj/fjILoTe6YVyqNhEnYIJk9OmMJkSXDKDHbiZAW413YgNtwA0kJf62LAuWMKqqwgUvB+nY4A6VvVGuGWCO3Rrftdsc5Lb3deuiSsEc1EfJDOae0YMOS04mksBNqobiXBkhwKS+p6T0v+vrlcxPbXnDSWJBl1YyGZG8f+OgF8vMxP5Kl6zSm3krpFH0u2MHK9/FykxwIn7Zx/KCbJu0wUJJQOI0lrbmg2iMdicrQAYzDX8+BfLzuQRtfVFylxchcTdeR6OrxkySPeFunVh5EO9YqJP7AtVnnLUtW78GIyStAYHAbQYyYZ3RWV2A5kpG1CiFNiaDih+QBdv6CN8LeLWC3Je4lAanuQO925kcE4GUPXvCIyQ7OV1ZHpDA6BE6wX9/2vnKj9z3phm8L0gsFxv4Hnc4X5oIaVqK/ewqjUuacdlRkBXaUHK+8YA9g+jTQd0NQV1QuIASFBaddwKuyA7fnMkQ1nqdIaorXQHnNi4mD8xXbXexABDCfnn34/mJ3ejUacggMcuGCkeqknHOzobzdZaaRcuqii/4i10k8gMQRg9JChpGaSfs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
