travis:
  secure:
    BINSTAR_TOKEN: jp8Jt/yk6UkEhDL15BSdHcTpXfzOP1/nxnRxWjZsYFbudHXvV51xAQwadnKG6Pdbcbc/fy3hcM8wXbXUqcjVsFxqzaGFsoGtcEKBh6LeKr8PsrGVl9MEbTI+dPT7VOJRv+enmuZ6CSDJEcjnx845YfSkkhF4dUW9DloS0ymaUTW4Cc7uA0QCU8SwIjZuGHGu7ADDM0yHO8m3x+XgTi83KnTs2HPC4Y6iI/i6n9AncZ0UxVqvpQTDFmoLcSYxgCUwiHTzzQURJEPapNAY9DW3N4sDppC+SxudtqHO6S/yoPdBn6OvjbxcOcLqxOrSjCPL4BcZl/33ZvPI6KWAKziT6BuQioljh6YtlIGTZkOH0Hpkx6ZQCE1tS3qd8UQf4jb/S5vrQnk9ACfGLzwUwmKFD8NzqOUAUKzZD5et7Ai7O/3CF/PyUA9mnPJS1JaBkEIaP0mhVgtYrDYlo71bvIV9RgYXEX5BJTNPGYy4JTWHQlJytQ3gBbohktNa3W/Vq6uWu11hweLECDYcKTH/FYPSGqDgdqPGbV+cTo3a8bOaEMFn2Ya1GvkY5vrH6lDskA6nYIYZRhCFUEqJvPbEoDxU/Zm3gVG49XUjY4IS5InjV2pjUn5SkZFMRO6s49MIOxcv5RGvU/FjDvxYUzll2lPbPr/RtS8nlqhgulj6Ie/7pUc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
