travis:
  secure:
    BINSTAR_TOKEN: YqRV20Ou/737GaffyBUIJiVpOW/pZGrgifsJ41WNBLUqQ36esutFDYoh2wBAUAUhPhjvlDBAl7vuimBSiRLYNCdJLdjmbxvQpfKEuy0cvM51HwVl+g5EVj/fjILoTe6YVyqNhEnYIJk9OmMJkSXDKDHbiZAW413YgNtwA0kJf62LAuWMKqqwgUvB+nY4A6VvVGuGWCO3Rrftdsc5Lb3deuiSsEc1EfJDOae0YMOS04mksBNqobiXBkhwKS+p6T0v+vrlcxPbXnDSWJBl1YyGZG8f+OgF8vMxP5Kl6zSm3krpFH0u2MHK9/FykxwIn7Zx/KCbJu0wUJJQOI0lrbmg2iMdicrQAYzDX8+BfLzuQRtfVFylxchcTdeR6OrxkySPeFunVh5EO9YqJP7AtVnnLUtW78GIyStAYHAbQYyYZ3RWV2A5kpG1CiFNiaDih+QBdv6CN8LeLWC3Je4lAanuQO925kcE4GUPXvCIyQ7OV1ZHpDA6BE6wX9/2vnKj9z3phm8L0gsFxv4Hnc4X5oIaVqK/ewqjUuacdlRkBXaUHK+8YA9g+jTQd0NQV1QuIASFBaddwKuyA7fnMkQ1nqdIaorXQHnNi4mD8xXbXexABDCfnn34/mJ3ejUacggMcuGCkeqknHOzobzdZaaRcuqii/4i10k8gMQRg9JChpGaSfs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
