travis:
  secure:
    BINSTAR_TOKEN: Q3tZEtiMkR9wW/DMlbKgZu6una67+gr/snNZJPhK29rocK2BXG9J+NLzfAe7EiA7QDhPjxYkm2MMEYwD4kJM3o1g02Bznz9wyh5pQrYE4YsdvKrzQXmdE1ZakNjC3mR+y43Zp+2o2782d3co3S8q8DIGnORtWYTTTrT6qqDvDxpmfejFLtzCUKLWINeGRD6CWchZ9D23K2OjUWU1XgkvwlW6VZ9I3VAbcUN8qEJQFJnApSFa3lbLsX2/OZ+yDExx+kcsI4fo4uAHJMjiSrooMLybU8cvRUzCud4OtMvN0jLG01uqTplDGJ4PZU4FFnkBaoxIGtUgFUoERC+oYxWYxDJalkYgyHHxWBrqPQBQsq3p8NbpzfiBoIA8Ytr7POWHGl0ilhdbiPNsgTHn91oTDQx9aQd6PHO/3vQcvtGgSKsoRA+IdKJFmRlEyjZBG/ArHm9LFvX0s6eGfHoy5xDUBy77aiAvo3QDZayTFWglLWEdHO8bQJhu71pqSBH/LeRDTzBupg1ElCzIp2OiWk+L1XClA4oYQDX8X9GkW1ZR+tBGRnuSIOSwrmseyuMXpifO2yAGsvZR/zy2XGfsV4bJabQzkTahzKuAfqFuP76goDOFWX2inVvfgVZmellEm3cYxhQleieeYRl9pvAhuQmHIN7otg8I27+mMpybs/hZXu8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
